// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIZyXZxOlzv-YbGR4W4zjhDmJYI37mOKM',
    appId: '1:878359658181:web:a3285bd5c6e27bc565faac',
    messagingSenderId: '878359658181',
    projectId: 'agri-37771',
    authDomain: 'agri-37771.firebaseapp.com',
    storageBucket: 'agri-37771.appspot.com',
    measurementId: 'G-145BM0GS44',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsnrY9kKauHg-QmSwayX1rqOk9lpBz2lQ',
    appId: '1:878359658181:android:f03bdb33b6b40db265faac',
    messagingSenderId: '878359658181',
    projectId: 'agri-37771',
    storageBucket: 'agri-37771.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLixKQDlN77h7202ppmBUXl6ssYl61tOE',
    appId: '1:878359658181:ios:a0eb356c1e2d680765faac',
    messagingSenderId: '878359658181',
    projectId: 'agri-37771',
    storageBucket: 'agri-37771.appspot.com',
    iosClientId: '878359658181-5j1kb81kkvf74gtaco73rpg4hq791lca.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );
}
